//
//  File.swift
//  Phi6 Alpha
//
//  Created by Giuseppe Sannino on 08/02/2017.
//  Copyright © 2017 Salvatore Capuozzo. All rights reserved.
//

import Foundation

var Lesson =
    [
        //Cinematics
        [
            "• La traiettoria luogo dei punti occupati successivamente dal punto in movimento costituisce una curva continua nello spazio ed e’ rappresentata matematicamente dalla funzione \n• Spazio percorso e la misura del cammino percorso a partire dalla posizione iniziale P0. \n• Velocità, variazione di posizione lungo la traiettoria in funzione del tempo. \n• Accelerazione. Lo studio delle variazioni della velocità con il tempo introduce la grandezza • Tempo percorso dall istante iniziale spesso usato come variabile indipendente, in funzione di cui si esprimono le altre grandezze \n• La quiete è un caso particolare di moto in cui le coordinate restano costanti e quindi velocità e accelerazione sono nulle. Il concetto di quiete e di moto e tuttavia un concetto relativo al sistema di riferimento adottato. Di norma la traiettoria di una particella in moto ha una forma diversa ed è rappresentata matematicamente da unequazione diversa in diversi sistemi di riferimento.",
            "Moto rettilineo\n\n• Si svolge lungo una retta sulla quale vengono fissati arbitrariamente un'origine e un verso \n• Il moto del punto è descrivibile in funzione del tempo tramite una sola coordinata x(t), come rappresentato in figura 1.1. Lo spazio varia a partire da un posizione iniziale x0 e cresce in funzione del tempo, Matematicamente, si dice che lo spazio e’ una funzione del tempo e si indica con x = x(t) \n• Sperimentalmente x(t) può essere determinata ponendo lungo la retta dei traguardi con dispositivi a cellula fotoelettrica collegati ad un cronometro \n• Si ottengono coppie di valori x e t che costituiscono il diagramma orario del moto. Diagramma orario x(t) = -2m x(t) = -2+0.5(t -3)2 per 0<t<3s per 3s<t<3s x(t) = +7 x(t) = 6-2(t –10) per 7s<t<10s per 10s<t<13s",
            "Moto parabolico (moto di un proiettile)\n\n• Si ha quando il vettore velocità v0 è obliquo rispetto al vettore accelerazione g.\n• E\' dato dalla sovrapposizione di due moti:\n\t• un moto rettilineo uniforme orizzontale;\n\t• e un modo rettilineo uniformemente accelerato verticale.\n\nVelocità iniziale orizzontale\ny = -(1/2)(g/v0^2)x^2\n• v0 è la velocità iniziale orizzontale;\n• g è l'accelerazione di gravità.\n• La traiettoria di un oggetto lanciato in orizzontale è una parabola con il vertice nel punto di lancio."
        ],
        //Dynamics
        [
            "• La Dinamica studia il moto dei corpi in relazione il moto con le sue cause: perche e come gli oggetti si muovono. \n• La causa del moto `e individuata nella presenza di interazioni fra corpi che si manifestano come Forze \n• Il moto dei corpi `e determinato dalle Leggi di Newton,Elemento",
            "• La prima legge di Newton descrive cosa succede in assenza di interazioni\n\n• Per un oggetto non interagente con altri oggetti, `e sempre possibile identificare un sistema di riferimento, detto inerziale, nel quale l’oggetto ha accelerazione nulla.\n• In assenza di interazioni con l’esterno, un oggetto permane nel suo stato di quiete o di moto a velocit`a costante, se osservato da un sistema di riferimento inerziale\n\nNota anche come Principio di Inerzia.\nSe m indica la massa di un corpo e F la risultante delle forze agenti su di esso, la legge di Newton, nota anche come legge fondamentale della dinamica, si scrive nel modo seguente\n\nF = ma\n\nove a e\' il vettore accelerazione.\n• La precedente equazione va considerata come definizione di forza agente su di un punto materiale. Dalla sua definizione risulta che l’unit`a di misura della forza `e kg m/s2, che viene convenzionalmente detto newton, simbolo N."
        ],
        //Statica
        [
            "Si chiama punto materiale un oggetto ideale con dimensioni nulle (o meglio trascurabili rispetto alle dimensioni dei fenomeni considerati e quindi paragonabile ad un punto materiale) ma dotato di massa.\n\nIl primo principio della dinamica afferma che:\nUn punto materiale persevera nel suo stato di quiete o di moto rettilineo uniforme se la risultante delle forze su di lui applicate è un vettore nullo(cioè se le forze si oppongono annullandosi)\n\n∑i(Fi)=0\n\nBisogna tenere presente che per l'equilibrio di un corpo rigido non basta che il risultante delle forze sia nullo ma che anche il risultante dei momenti delle forze applicate sia nullo. In effetti due forze uguali ed opposte ma applicate in due punti del corpo non assiali creano un momento non nullo. Dunque accanto alla formula sopra scritta va aggiunta:\n\n∑i(Mi)=0\n\nNel caso di sistemi generali, composti da diversi punti materiali e diversi corpi rigidi, il criterio di equilibrio necessita che ogni singolo punto materiale ed ogni singolo corpo rigido deve essere in equilibrio. Questo significa che per un sistema materiale non è sufficiente per avere l'equilibrio che il risultante delle forze esterne ed il momento totale delle forze esterne siano nulli. Questa è solo una condizione necessaria.",
            "Reazione del supporto e attrito statico\n\nIn numerosi problemi semplici, la reazione del supporto è perpendicolare alla sua superficie. Questo è vero solo per un oggetto immobile su una superficie senza attrito. Così, per esempio, supponiamo un oggetto appoggiato su un piano inclinato perfettamente scivoloso (oppure una biglia che possa rotolare senza resistenze) e tenuto per un cavo, allora la reazione del supporto è perfettamente perpendicolare ad esso.\n\nMa la situazione è diversa nel caso di un oggetto immobile su un piano inclinato, senza cavo, trattenuto unicamente dall'attrito; la reazione R del supporto compensa allora solo il peso. In questo caso, si può scomporre la reazione in una componente Rn perpendicolare al supporto e una Rf ad esso parallela. Rf è detta forza di attrito statico.\n\nUn altro caso in cui la forza non è perpendicolare al supporto:\nl'intensità della forza di attrito statico è determinata solitamente mediante la teoria di Coulomb, secondo la quale la massima componente parallela alle superfici di contatto è direttamente proporzionale all'intensità della forza scambiata tra le stesse superfici, mediante il coefficiente di attrito statico.\n\nLa Forza d'attrito statico(Fs) è dato dalla seguente formula: \n\nFs = us mg\n\ndove us è il coefficiente di attrito statico, ed m e g sono rispettivamente la massa dell'oggetto e l'accelerazione di gravità"
        ]
]

var englishLesson = [
    [
        //Kinematics
        "• The location of the trajectory points successively occupied by the moving point is a continuous curve in space and is mathematically represented by the function \n • Space path and the extent of the progress made since the initial position P0. \n • Speed, variation in position along the trajectory as a function of time. \n • Acceleration. The study of how speed changes • Travel time from initial time often used as an independent variable, a function for which you express the other quantities \n • Rest is a special case of motion in which the coordinates remain constant and then speed and acceleration are zero. The concept of stillness and motion, yet a concept relevant to the intended reference system. Normally the trajectory of a particle in motion has a different shape and is mathematically represented by different unequazione in different reference systems.",
        "Rectilinear motion \n\n • It takes place along a straight line on which an origin and a direction are arbitrarily chosen \n • The motion of the point is describable as a function of time through a single coordinate x (t), as represented in Figure 1.1 . The space varies from an initial position x0 and grows as a function of time, Mathematically, it is said that the space is a function of time and is denoted by x = x (t) \n • Experimentally x (t) can be determined by placing along the line of targets with a photodetector devices connected to a timer \n • get pairs of x and t values that make up the diagram in clockwise motion. x Time (t) diagram = -2m x (t) = -2 + 0.5 (t -3) 2 for 0 <t <3s for 3s <t <3s x (t) = +7 x (t) = 6- 2 (t -10) to 7s <t <10s to 10s <t <13s",
        "Parabolic motion (motion of a projectile) \n\n • It has v0 when the velocity vector is oblique with respect to the acceleration vector g. \n • It\'s given by the superposition of two motions: \n\t • a rectilinear  horizontal uniform motion; \n\t • and a rectilinear uniformly accelerated vertical motion.\n\n horizontal initial \n Speed \n y = - (1/2) (g / v0 ^ 2) x ^ 2 \n • v0 is the initial horizontal speed ; \n • g is the acceleration of gravity. \n • the trajectory of an object launched horizontally is a parabola with the vertex in the launching point. "
        
    ],
    [
        //dynamics
        "Dynamics studies the motion of bodies in relation to the motion and its causes: why and how objects move. \n • The cause of motion is identified in the presence of interactions between bodies that manifest themselves as forces \n • The motion of bodies is determined by the Laws of Newton",
        "• Newton's First Law describes what happens in the absence of interactions \n\n • For an object who doesn't' interact with other objects, it\'s always possible to identify a reference system, called inertial, in which the object has zero acceleration. \n • in the absence of interaction with the outside world, an object persists in its state of rest or in constant motion, if viewed from an inertial reference system \n\n This is called the Principle of Inertia. \n If m indicates the mass of a body and the resultant F of the forces acting on it, Newton's law, also known as the fundamental law of dynamics, you write the following \n\n F = ma \n\n where a is the acceleration vector. \n • The previous equation must be considered as a definition of force acting on a material point. From its definition that the unit`a measurement of strength and kg m / s2, which is conventionally said newton, has symbol N."
    ],
    [
        //statics
        "An ideal point is an object with zero size (or rather insignificant compared to the size of the problem and therefore comparable to a material point) but with mass. \n\n The first law of motion states that: \n A material point perseveres in its state of rest or uniform rectilinear motion if the resultant of the forces applied on him is a zero vector (ie if the forces are opposed canceling) \n \n Σi (Fi) = 0 \n\n You must keep in mind that for the balance of a rigid body is not sufficient that the resultant of the forces is zero but also that the resultant of the moments of the applied forces is zero. In fact two equal and opposite forces, but applied at two non axial points create a non null moment. So next to the formula written above should be added: \n\n Σi (I) = 0 \n\n In case of general systems, which consist of several material points and several rigid bodies, the equilibrium criterion requires that each and every material point and each rigid body must be in balance. This means that, for a material system it is not sufficient to have the balance that the resultant of the external forces and the total moment of the external forces are zero. This is only a necessary condition. ",
        "Reaction of the support and static friction \n\n In numerous simple problems, the reaction of the substrate is perpendicular to its surface. This is only true for a motionless object on a frictionless surface. Thus, for example, suppose that an object is resting on a inclined perfectly slippery floor (or a ball that can roll without resistors) and is held for a cable, then the reaction of the substrate is perfectly perpendicular to it. \n\n BUT the situation is different in the case of a motionless object on an inclined plane, without cable, retained solely by friction; the reaction R of the support compensates then only the weight. in this case, the reaction can be decomposed into a component perpendicular to the support Rn and a Rf parallel thereto. Rf is said force of static friction . \n\n  !nother case in which the force is not perpendicular to the support: \n The intensity of the force of static friction is usually determined by means of the Coulomb theory, according to which the maximum component parallel to the contact surfaces is directly proportional to the intensity of the force exchanged between the same surfaces, using the coefficient of static friction. \n\n The static friction force (Fs) is given by the following formula: \n\n FS = us mg \n\n where us is the coefficient of static friction, and m and g are respectively the mass and the acceleration of gravity"
    ]
]
